version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - data-volume:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: levtech2023
      MYSQL_DATABASE: guest-house
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: levtech2023
      TZ: 'Asia/Tokyo'


  django:
    build: .
    tty: true
    volumes:
      - ./guesthouse:/django
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db

volumes:
  data-volume: